export const VCA_GAIN_CHANGE = "VCA_GAIN_CHANGE";

export const NOISE_GAIN_CHANGE = "NOISE_GAIN_CHANGE";
export const NOISE_PAN_CHANGE = "NOISE_PAN_CHANGE";
export const NOISE_TOGGLE = "NOISE_TOGGLE";

export const SUB_GAIN_CHANGE = "SUB_GAIN_CHANGE";
export const SUB_PAN_CHANGE = "SUB_PAN_CHANGE";
export const SUB_TOGGLE = "SUB_TOGGLE";
export const SUB_DEPTH_CHANGE = "SUB_DEPTH_CHANGE";

export const KEYBOARD_LAYOUT_CHANGE = "KEYBOARD_LAYOUT_CHANGE";
export const KEYBOARD_PITCH_SHIFT = "KEYBOARD_PITCH_SHIFT";
export const KEYBOARD_CHORD_SHIFT = "KEYBOARD_CHORD_SHIFT";
export const KEYBOARD_KEY_DOWN = "KEYBOARD_KEY_DOWN";
export const KEYBOARD_KEY_UP = "KEYBOARD_KEY_UP";

export const CHORD_SHIFT_ENABLE = "CHORD_SHIFT_ENABLE";
export const CHORD_SHIFT_DISABLE = "CHORD_SHIFT_DISABLE";

export const MIDI_KEY_DOWN = "MIDI_KEY_DOWN";
export const MIDI_KEY_UP = "MIDI_KEY_UP";
export const MIDI_ADD_INPUT_PORT = "MIDI_ADD_INPUT_PORT";
export const MIDI_PORT_SELECT = "MIDI_PORT_SELECT";
export const MIDI_UNAVAILABLE = "MIDI_UNAVAILABLE";
export const MIDI_BANK_SELECT = "MIDI_BANK_SELECT";
export const MIDI_PITCHBEND = "MIDI_PITCHBEND";
export const MIDI_MODULATION_WHEEL = "MIDI_MODULATION_WHEEL";
export const MIDI_BREATH_CONTROLLER = "MIDI_BREATH_CONTROLLER";
export const MIDI_FOOT_PEDAL = "MIDI_FOOT_PEDAL";
export const MIDI_PORTAMENTO_TIME = "MIDI_PORTAMENTO_TIME";
export const MIDI_DATA_ENTRY = "MIDI_DATA_ENTRY";
export const MIDI_VOLUME = "MIDI_VOLUME";
export const MIDI_BALANCE = "MIDI_BALANCE";
export const MIDI_PAN_POSITION = "MIDI_PAN_POSITION";
export const MIDI_EXPRESSION = "MIDI_EXPRESSION";
export const MIDI_EFFECT_CONTROL_1 = "MIDI_EFFECT_CONTROL_1";
export const MIDI_EFFECT_CONTROL_2 = "MIDI_EFFECT_CONTROL_2";



export const SYNC_NUMERATOR_CHANGE = "SYNC_NUMERATOR_CHANGE";
export const SYNC_DENOMINATOR_CHANGE = "SYNC_DENOMINATOR_CHANGE";
export const SYNC_TOGGLE = "SYNC_TOGGLE";

export const ENVELOPE_POINT_DELETE = "ENVELOPE_POINT_DELETE";
export const ENVELOPE_POINT_ADD = "ENVELOPE_POINT_ADD";
export const ENVELOPE_POINT_EDIT_START = "ENVELOPE_POINT_EDIT_START";
export const ENVELOPE_POINT_EDIT_END = "ENVELOPE_POINT_EDIT_END";
export const ENVELOPE_POINT_CHANGE = "ENVELOPE_POINT_CHANGE";
export const ENVELOPE_SUSTAIN_CHANGE = "ENVELOPE_SUSTAIN_CHANGE";
export const ENVELOPE_SUSTAIN_EDIT_START = "ENVELOPE_SUSTAIN_EDIT_START";
export const ENVELOPE_SUSTAIN_EDIT_END = "ENVELOPE_SUSTAIN_EDIT_END";
export const ENVELOPE_MODE_CHANGE = "ENVELOPE_MODE_CHANGE";
export const ENVELOPE_DURATION_CHANGE = "ENVELOPE_DURATION_CHANGE";
export const ENVELOPE_BLUR = "ENVELOPE_BLUR";

export const LFO_RESET = "LFO_RESET";
export const LFO_FREQUENCY_CHANGE = "LFO_FREQUENCY_CHANGE";
export const LFO_WAVEFORM_CHANGE = "LFO_WAVEFORM_CHANGE";
export const LFO_AMOUNT_CHANGE = "LFO_AMOUNT_CHANGE";

export const OSCILLATOR_DETUNE_CHANGE = "OSCILLATOR_DETUNE_CHANGE";
export const OSCILLATOR_MIX_CHANGE = "OSCILLATOR_MIX_CHANGE";
export const OSCILLATOR_WRAPPER_CHANGE = "OSCILLATOR_RESONANCE_CHANGE";
export const OSCILLATOR_WAVEFORM_CHANGE = "OSCILLATOR_WAVEFORM_CHANGE";
export const OSCILLATOR_RESONANCE_FACTOR_CHANGE = "OSCILLATOR_RESONANCE_FACTOR_CHANGE";
export const OSCILLATOR_RESONANCE_TOGGLE = "OSCILLATOR_RESONANCE_TOGGLE";

export const MODULATION_CONNECTION_TOGGLE = "MODULATION_CONNECTION_TOGGLE";
export const MODULATION_POLARITY_CHANGE = "MODULATION_POLARITY_CHANGE";
export const MODULATION_AMOUNT_CHANGE = "MODULATION_AMOUNT_CHANGE";


