export * as CHORD_SHIFT from "./actions/chord-shift-actions";
export * as MIDI from "./actions/midi-actions";


export const SET_SYSTEM_CONFIGURATION = "SET_SYSTEM_CONFIGURATION";
export const SYSTEM_RESET = "SYSTEM_RESET";
export const BASE_FREQUENCY_CHANGE = "BASE_FREQUENCY_CHANGE";
export const TUNING_SELECT_SCALE = "TUNING_SELECT_SCALE";
export const BASE_KEY_CHANGE = "BASE_KEY_CHANGE";
export const SCALE_BASE_CHANGE = "SCALE_BASE_CHANGE";
export const SCALE_TYPE_CHANGE = "SCALE_TYPE_CHANGE";
export const SCALE_NOTE_COUNT_CHANGE = "SCALE_NOTE_COUNT_CHANGE";
export const SCALE_FACTOR_CHANGE = "SCALE_FACTOR_CHANGE";


export const VCA_GAIN_CHANGE = "VCA_GAIN_CHANGE";

export const NOISE_COLOR_CHANGE = "NOISE_COLOR_CHANGE";

export const OUTPUT_GAIN_CHANGE = "OUTPUT_GAIN_CHANGE";
export const OUTPUT_PAN_CHANGE = "OUTPUT_PAN_CHANGE";
export const OUTPUT_TOGGLE = "OUTPUT_TOGGLE";

export const SUB_DEPTH_CHANGE = "SUB_DEPTH_CHANGE";
export const SUB_BEAT_FREQUENCY_CHANGE = "SUB_BEAT_FREQUENCY_CHANGE";
export const SUB_DETUNE_CHANGE = "SUB_DETUNE_CHANGE";
export const SUB_DETUNE_MODE_CHANGE = "SUB_DETUNE_MODE_CHANGE";


export const KEYBOARD_LAYOUT_CHANGE = "KEYBOARD_LAYOUT_CHANGE";
export const KEYBOARD_PITCH_SHIFT = "KEYBOARD_PITCH_SHIFT";
export const KEYBOARD_CHORD_SHIFT = "KEYBOARD_CHORD_SHIFT";
export const KEYBOARD_CHORD_SHIFT_TOGGLE = "KEYBOARD_CHORD_SHIFT_TOGGLE";
export const KEYBOARD_KEY_DOWN = "KEYBOARD_KEY_DOWN";
export const KEYBOARD_KEY_UP = "KEYBOARD_KEY_UP";




export const SYNC_NUMERATOR_CHANGE = "SYNC_NUMERATOR_CHANGE";
export const SYNC_DENOMINATOR_CHANGE = "SYNC_DENOMINATOR_CHANGE";
export const SYNC_TOGGLE = "SYNC_TOGGLE";

export const ENVELOPE_POINT_DELETE = "ENVELOPE_POINT_DELETE";
export const ENVELOPE_POINT_ADD = "ENVELOPE_POINT_ADD";
export const ENVELOPE_POINT_EDIT_START = "ENVELOPE_POINT_EDIT_START";
export const ENVELOPE_POINT_EDIT_END = "ENVELOPE_POINT_EDIT_END";
export const ENVELOPE_POINT_CHANGE = "ENVELOPE_POINT_CHANGE";
export const ENVELOPE_SUSTAIN_CHANGE = "ENVELOPE_SUSTAIN_CHANGE";
export const ENVELOPE_SUSTAIN_EDIT_START = "ENVELOPE_SUSTAIN_EDIT_START";
export const ENVELOPE_SUSTAIN_EDIT_END = "ENVELOPE_SUSTAIN_EDIT_END";
export const ENVELOPE_MODE_CHANGE = "ENVELOPE_MODE_CHANGE";
export const ENVELOPE_DURATION_CHANGE = "ENVELOPE_DURATION_CHANGE";
export const ENVELOPE_BLUR = "ENVELOPE_BLUR";

export const MODULATOR_RESET = "MODULATOR_RESET";
export const MODULATOR_FREQUENCY_CHANGE = "MODULATOR_FREQUENCY_CHANGE";
export const MODULATOR_AMOUNT_CHANGE = "MODULATOR_AMOUNT_CHANGE";
export const MODULATOR_MODE_CHANGE = "MODULATOR_MODE_CHANGE";

export const LFO_WAVEFORM_CHANGE = "LFO_WAVEFORM_CHANGE";

export const MORSE_TEXT_CHANGE = "MORSE_TEXT_CHANGE";
export const MORSE_SPEED_UNIT_CHANGE = "MORSE_SPEED_UNIT_CHANGE";
export const MORSE_GUIDE_TOGGLE = "MORSE_GUIDE_TOGGLE";
export const MORSE_SHIFT_CHANGE = "MORSE_SHIFT_CHANGE";
export const MORSE_PADDING_CHANGE = "MORSE_PADDING_CHANGE";
export const MORSE_FILL_TOGGLE = "MORSE_FILL_TOGGLE";


export const OSCILLATOR_DETUNE_CHANGE = "OSCILLATOR_DETUNE_CHANGE";
export const OSCILLATOR_MIX_CHANGE = "OSCILLATOR_MIX_CHANGE";
export const OSCILLATOR_WRAPPER_CHANGE = "OSCILLATOR_RESONANCE_CHANGE";
export const OSCILLATOR_WAVEFORM_CHANGE = "OSCILLATOR_WAVEFORM_CHANGE";
export const OSCILLATOR_RESONANCE_FACTOR_CHANGE = "OSCILLATOR_RESONANCE_FACTOR_CHANGE";
export const OSCILLATOR_MODE_CHANGE = "OSCILLATOR_MODE_CHANGE";

export const OSCILLATOR_RESONANCE_TOGGLE = "OSCILLATOR_RESONANCE_TOGGLE";

export const HARMONIC_NUMERATOR_CHANGE = "HARMONIC_NUMERATOR_CHANGE";
export const HARMONIC_DENOMINATOR_CHANGE = "HARMONIC_DENOMINATOR_CHANGE";
export const HARMONIC_LEVEL_CHANGE = "HARMONIC_LEVEL_CHANGE";
export const HARMONIC_LEVELS_NORMALIZE = "HARMONIC_LEVELS_NORMALIZE";
export const HARMONIC_TOGGLE = "HARMONIC_TOGGLE";
export const HARMONIC_PHASE_CHANGE = "HARMONIC_PHASE_CHANGE";
export const HARMONIC_NEW = "HARMONIC_NEW";
export const HARMONIC_ADD = "HARMONIC_ADD";
export const HARMONIC_REMOVE = "HARMONIC_REMOVE";

export const MODULATION_CONNECTION_TOGGLE = "MODULATION_CONNECTION_TOGGLE";
export const MODULATION_POLARITY_CHANGE = "MODULATION_POLARITY_CHANGE";
export const MODULATION_AMOUNT_CHANGE = "MODULATION_AMOUNT_CHANGE";

