const prefix = "AUDIOFILE_WAV_";
const SAMPLERATE_CHANGE = prefix + "SAMPLERATE_CHANGE";
const RESOLUTION_CHANGE = prefix + "RESOLUTION_CHANGE";
const FILENAME_CHANGE = prefix + "FILENAME_CHANGE";

export {
    FILENAME_CHANGE,
    SAMPLERATE_CHANGE,
    RESOLUTION_CHANGE
};
