export const NOISE_GAIN_CHANGE = "NOISE_GAIN_CHANGE";
export const NOISE_PAN_CHANGE = "NOISE_PAN_CHANGE";
export const NOISE_TOGGLE = "NOISE_TOGGLE";

export const SUB_GAIN_CHANGE = "SUB_GAIN_CHANGE";
export const SUB_PAN_CHANGE = "SUB_PAN_CHANGE";
export const SUB_TOGGLE = "SUB_TOGGLE";
export const SUB_DEPTH_CHANGE = "SUB_DEPTH_CHANGE";

export const KEYBOARD_LAYOUT_CHANGE = "KEYBOARD_LAYOUT_CHANGE";

export const MIDI_ADD_INPUT_PORT = "MIDI_ADD_INPUT_PORT";
export const MIDI_PORT_SELECT = "MIDI_PORT_SELECT";
export const MIDI_UNAVAILABLE = "MIDI_UNAVAILABLE";

export const ENVELOPE_POINT_DELETE = "ENVELOPE_POINT_DELETE";
export const ENVELOPE_POINT_ADD = "ENVELOPE_POINT_ADD";
export const ENVELOPE_POINT_EDIT_START = "ENVELOPE_POINT_EDIT_START";
export const ENVELOPE_POINT_EDIT_END = "ENVELOPE_POINT_EDIT_END";
export const ENVELOPE_POINT_CHANGE = "ENVELOPE_POINT_CHANGE";
export const ENVELOPE_SUSTAIN_CHANGE = "ENVELOPE_SUSTAIN_CHANGE";
export const ENVELOPE_SUSTAIN_EDIT_START = "ENVELOPE_SUSTAIN_EDIT_START";
export const ENVELOPE_SUSTAIN_EDIT_END = "ENVELOPE_SUSTAIN_EDIT_END";
export const ENVELOPE_MODE_CHANGE = "ENVELOPE_MODE_CHANGE";
export const ENVELOPE_DURATION_CHANGE = "ENVELOPE_DURATION_CHANGE";
export const ENVELOPE_BLUR = "ENVELOPE_BLUR";