export const NOISE_GAIN_CHANGE = "NOISE_GAIN_CHANGE";
export const NOISE_PAN_CHANGE = "NOISE_PAN_CHANGE";
export const NOISE_TOGGLE = "NOISE_TOGGLE";
export const KEYBOARD_LAYOUT_CHANGE = "KEYBOARD_LAYOUT_CHANGE";